model = "gpt-5-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]
projects = { "/Users/sfurukawa/Workspace/private/trello-mcp-server" = { trust_level = "trusted" } }

[tools]
web_search = true

